import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import MainMenu, { type MenuItemType } from "./components/menu/mainMenu";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const menuItems: Array<MenuItemType> = [
    {
        text: "Závody",
        link: "/",
        adminOnly: false
    },
    {
        text: "Přihlášky",
        link: "/prihlasky",
        adminOnly: false
    },
    {
        text: "Zápis výkonů",
        link: "/zavody",
        adminOnly: true
    },
    {
        text: "Nový závod",
        link: "/zavody/novy",
        adminOnly: true
    }
]

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="cs" className={`${GeistSans.variable}`}>
            <body>
                <header>
                    <MainMenu menuItems={menuItems} isAdmin={true}/>
                </header>
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
