import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "~/components/theme/theme-provider"
import MainMenu, { type MenuItemType } from "~/components/menu/mainMenu";
import { Toaster } from "~/components/ui/sonner"
import { HydrateClient } from "~/trpc/server";
import { getServerAuthSession } from "~/server/auth"

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const menuItems: Array<MenuItemType> = [
    {
        text: "Závody",
        link: "/",
        adminOnly: false
    },
    {
        text: "Zápis výkonů",
        link: "/zavod",
        adminOnly: true
    }
]

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const session = await getServerAuthSession()

    return (
        <html lang="cs" className={`${GeistSans.variable}`} suppressHydrationWarning>
            <body>
                <TRPCReactProvider>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange >
                        <header>
                            <MainMenu menuItems={menuItems} isAdmin={session !== null}/>
                        </header>
                        <main>
                            <HydrateClient>
                                {children}
                            </HydrateClient>
                        </main>
                        <Toaster />
                    </ThemeProvider>
                </TRPCReactProvider>
            </body>
        </html>
    );
}
